version: '3'
services:
  web:
    image: 2.3-slim-jessie
    build: .
    entrypoint: /accounts-service/docker-entrypoint.sh
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
    - .:/accounts-service
    ports:
    - "3001:3001"